### ISSUE TITLE
Possibilities of cheating and plagiarism

### ISSUE THREAD

**Issue by herpiko** [devsalman/uts-web#2]
Hi, 

How do you prevent the cheats? Once a submitter push his/her code, the others could fetch it, modify it a bit and claim that it was their work.

If you say that you will review all the submissions and detect the cheat(s) yourself, I suggest you to use a pull request as submission. A github's PR gave us straight comparison and made code review easier. The other benefit is the submitter could get more knowledge about how git, github and open contribution works.

**Comment by devsalman** [comment]
Hi @herpiko,

Yeah you right, even in paper submission they can find a way how to cheat without getting noticed from the teacher or supervisor. The main problem is not about how to prevent them from cheating but how to educate them that cheating is just make their future worse.

About the git fetch and merge from other repository, i'm still not sure if they now this method because they just still beginner in git / github world. But i'll try my best to review the submission and give a fair judgement to their work

**Comment by herpiko** [comment]
> About the git fetch and merge from other repository, i'm still not sure if they now this method because they just still beginner in git / github world.

Makes sense. I didn't realize that until now. Thank you for your response.
